/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SShareSlugRouteImport } from './routes/s/$shareSlug'
import { Route as FSlugRouteImport } from './routes/f/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareSlugRoute = SShareSlugRouteImport.update({
  id: '/s/$shareSlug',
  path: '/s/$shareSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/f/$slug': typeof FSlugRoute
  '/s/$shareSlug': typeof SShareSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/f/$slug': typeof FSlugRoute
  '/s/$shareSlug': typeof SShareSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/f/$slug': typeof FSlugRoute
  '/s/$shareSlug': typeof SShareSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/f/$slug' | '/s/$shareSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/f/$slug' | '/s/$shareSlug'
  id: '__root__' | '/' | '/f/$slug' | '/s/$shareSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FSlugRoute: typeof FSlugRoute
  SShareSlugRoute: typeof SShareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareSlug': {
      id: '/s/$shareSlug'
      path: '/s/$shareSlug'
      fullPath: '/s/$shareSlug'
      preLoaderRoute: typeof SShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FSlugRoute: FSlugRoute,
  SShareSlugRoute: SShareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
