services:
  filex:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file: /srv/docker/secrets/filex.env
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      mongo:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - filex

  filex-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - filex
    restart: unless-stopped
    networks:
      - filex

  mongo:
    image: mongo:8
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping:1})"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - filex

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - filex

networks:
  filex:

volumes:
  mongo_data:
  minio_data: