services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: filex-server
    env_file: /srv/docker/secrets/filex.env
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - internal

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: filex-client
    depends_on:
      - server
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
    external: true